import { requireAuthApi, isAuthError } from '@/lib/auth/api'
import { createServiceClient } from '@/lib/supabase/service'
import { NextResponse } from 'next/server'

type SubItemValue = {
  column_id: string
  col_key: string
  value_text: string | null
  value_number: number | null
  value_date: string | null
  value_json: unknown
}

type SubItemData = {
  id: string
  sid: number
  parent_id: string | null
  depth: 0 | 1
  name: string
  source_item_id: string | null
  position: number
  values: SubItemValue[]
}

type Context = { params: Promise<{ id: string }> }

function cartesian(arrays: string[][]): string[][] {
  return arrays.reduce<string[][]>(
    (acc, curr) => acc.flatMap(a => curr.map(b => [...a, b])),
    [[]]
  )
}

export async function POST(req: Request, { params }: Context) {
  const auth = await requireAuthApi()
  if (isAuthError(auth)) return auth

  const { id } = await params
  const body = await req.json() as { column_ids?: string[] }
  const { column_ids } = body

  if (!column_ids || column_ids.length === 0) {
    return NextResponse.json({ error: 'column_ids required' }, { status: 400 })
  }

  const service = createServiceClient()

  // Load the parent sub-item
  const { data: parentSubItem } = await service
    .from('sub_items')
    .select('id, item_id, workspace_id, depth, name')
    .eq('id', id)
    .single()

  if (!parentSubItem) {
    return NextResponse.json({ error: 'Sub-item not found' }, { status: 404 })
  }

  // Verify it's a depth-0 sub-item
  if (parentSubItem.depth !== 0) {
    return NextResponse.json(
      { error: 'Solo sub-items de profundidad 0 pueden expandirse' },
      { status: 400 }
    )
  }

  // Load column values for each column_id
  const dimensionArrays: string[][] = []

  for (const columnId of column_ids) {
    const { data: valueRow } = await service
      .from('sub_item_values')
      .select('value_json')
      .eq('sub_item_id', id)
      .eq('column_id', columnId)
      .maybeSingle()

    const dimension = Array.isArray(valueRow?.value_json)
      ? (valueRow.value_json as string[])
      : []

    dimensionArrays.push(dimension)
  }

  // Check if any dimension is empty
  if (dimensionArrays.some(d => d.length === 0)) {
    return NextResponse.json(
      { error: 'Una dimensión está vacía' },
      { status: 400 }
    )
  }

  // Compute cartesian product
  const combinations = cartesian(dimensionArrays)

  // Load existing L2 names for this parent
  const { data: existingL2s } = await service
    .from('sub_items')
    .select('name')
    .eq('parent_id', id)
    .eq('depth', 1)

  const existingNames = new Set((existingL2s ?? []).map(x => x.name))

  // Filter out combinations that already exist
  const toCreate: { name: string; combo: string[] }[] = []
  for (const combo of combinations) {
    const name = combo.join(' / ')
    if (!existingNames.has(name)) {
      toCreate.push({ name, combo })
    }
  }

  if (toCreate.length === 0) {
    return NextResponse.json({
      created: [],
      skipped: combinations.length,
    })
  }

  // Insert created sub-items
  const createdSubItems: SubItemData[] = []

  for (let i = 0; i < toCreate.length; i++) {
    const { name } = toCreate[i]

    // Insert sub_item (sid auto-generated by DB default)
    const { data: newSubItem, error: insertError } = await service
      .from('sub_items')
      .insert({
        workspace_id: parentSubItem.workspace_id,
        item_id: parentSubItem.item_id,
        parent_id: id,
        depth: 1,
        name,
        position: i,
      })
      .select('id, sid, parent_id, depth, name, source_item_id, position')
      .single()

    if (insertError || !newSubItem) {
      return NextResponse.json(
        { error: insertError?.message ?? 'Insert failed' },
        { status: 500 }
      )
    }

    // Note: The sid returned from insert might differ from the one we generated.
    // We'll use the one from the insert response.
    const itemValues: SubItemValue[] = []

    createdSubItems.push({
      id: newSubItem.id,
      sid: newSubItem.sid,
      parent_id: newSubItem.parent_id,
      depth: newSubItem.depth,
      name: newSubItem.name,
      source_item_id: newSubItem.source_item_id,
      position: newSubItem.position,
      values: itemValues,
    })
  }

  const skipped = combinations.length - toCreate.length

  return NextResponse.json(
    {
      created: createdSubItems,
      skipped,
    },
    { status: 201 }
  )
}
