-- Migration 013: Storage bucket for item file attachments
-- Bucket is private — access controlled via signed URLs generated by API routes

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'item-files',
  'item-files',
  false,
  52428800,  -- 50 MB per file
  null       -- all mime types allowed
)
ON CONFLICT (id) DO NOTHING;

-- RLS: only authenticated users can access objects in this bucket
-- Access control is enforced at API level (workspace isolation via signed URLs)
CREATE POLICY "authenticated users can upload item files"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'item-files');

CREATE POLICY "authenticated users can read item files"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'item-files');

CREATE POLICY "authenticated users can delete item files"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'item-files');
